apiVersion: v2
name: ingress-nginx
type: application
version: 0.0.1
appVersion: "1.0"

dependencies:
  - name: ingress-nginx
    version: 4.12.3
    repository: https://kubernetes.github.io/ingress-nginx