# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd:
  global:
    domain: "argocd.mllab.davidsfreun.de"

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - argocd.mllab.davidsfreun.de
#      annotations:
#        "nginx.ingress.kubernetes.io/backend-protocol": "HTTP"
    metrics:
      enabled: true

  notifications:
    enabled: true
    secret:
      create: false
    cm:
      create: false

  controller:
    metrics:
      enabled: true
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi

