# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - argocd.mllab.davidsfreun.de
  metrics:
    enabled: true

notifications:
  enabled: true
  secret:
    create: false
  cm:
    create: false

controller:
  metrics:
    enabled: true
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi

