# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
argo-cd:
  global:
    domain: "argocd.mllab.davidsfreun.de"

  configs:
    params:
      server.insecure: true
    secret:
      create: false
    existingSecret: argocd-admin

  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - argocd.mllab.davidsfreun.de
    metrics:
      enabled: true
    admin:
      existingSecret: argocd-admin
      existingSecretKey: password

  notifications:
    enabled: true
    secret:
      create: false
    cm:
      create: false

  controller:
    metrics:
      enabled: true
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi

