# https://github.com/amikos-tech/chromadb-chart/blob/main/charts/chromadb-chart/values.yaml
chromadb:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - host: "chromadb.mllab.davidsfreun.de"
        paths:
          - path: /
            pathType: ImplementationSpecific
    ingressClassName: "nginx"
  chromadb:
    auth:
      enabled: true
      existingSecret: "chromadb-auth"
      type: "token"
    server:
      httpPort: 8000
      cors:
        allowOrigins: ["*"]
      allowResetClient: true
      ui:
        enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    data:
      volumeSize: "10Gi"
      storageClass: gp3-retain