# https://github.com/amikos-tech/chromadb-chart/tree/main
chromadb:
  persistence:
    storageClass: gp3
    size: 20Gi
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - host: "chromadb.mllab.davidsfreun.de"
        paths:
          - path: /
            pathType: ImplementationSpecific
    ingressClassName: "nginx"
  auth:
    enabled: true
    existingSecret: "chromadb-auth"
    type: "token"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"