#!/bin/bash
# get pip to install & install dependencies
unset ALL_PROXY http_proxy https_proxy
pip install --upgrade pip
pip install -r requirements.txt # repo dependencies
export ALL_PROXY=socks5h://127.0.0.1:1055
export PIP_BREAK_SYSTEM_PACKAGES=1 # optional, in case of blinker issue
pip install -U --ignore-installed blinker



# 4) Install
pip install -r mapping-llm-censorship/requirements.txt

# 5) Clean up container space
pip cache purge
rm -rf ~/.cache/* /root/.cache/* $HOME/.huggingface/* 2>/dev/null