#!/bin/bash
# get pip to install & install dependencies
unset ALL_PROXY http_proxy https_proxy
pip install --upgrade pip
python3 -m pip install -U pip setuptools wheel pysocks
export PIP_BREAK_SYSTEM_PACKAGES=1 # optional, in case of blinker issue
pip install -U --ignore-installed blinker
pip install -r mapping-llm-censorship/requirements.txt

export ALL_PROXY=socks5://127.0.0.1:1055

# Clean up container space
pip cache purge
rm -rf ~/.cache/* /root/.cache/* $HOME/.huggingface/* 2>/dev/null