lobe-chat:
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: chat.mllab.davidsfreun.de
        paths:
          - path: /
            pathType: Prefix
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  persistence:
    enabled: true
    storageClass: "gp3"
    size: 10Gi
