external-secrets:
  installCRDs: true
  
  serviceAccount:
    create: true
    name: external-secrets-operator
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::115801844135:role/eks-mllab-external-secrets-irsa
  metrics:
    service:
      enabled: true
      port: 8080
  webhook:
    port: 9443
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

