open-webui:
  existingSecret: "open-webui"
  ingress:
    enabled: true
    host: "webui.mllab.davidsfreun.de"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3

  env:
#    - name: WEBUI_SECRET_KEY
#      valueFrom:
#        secretKeyRef:
#          name: open-webui
#          key: secret-key
#    - name: DEFAULT_USER_ROLE
#      value: "user"