apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ssh://git@git.neozocloud.com:10022/argocd/base.git
      targetRevision: HEAD
      ref: base_values

    - repoURL: ssh://git@git.neozocloud.com:10022/tenants/hsp.git
      targetRevision: HEAD
      ref: tenant_values

    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.6.2
      helm:
        valueFiles:
          - $base_values/AWS/load-balancer-controller/values.yaml
          - $tenant_values/argocd/prod/infrastructure/aws-load-balancer-controller/values.yaml

  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated: {}
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: aws-load-balancer-tls
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
        - /webhooks/2/clientConfig/caBundle
        - /webhooks/3/clientConfig/caBundle
        - /webhooks/4/clientConfig/caBundle
        - /webhooks/5/clientConfig/caBundle