apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: hsp
  source:
    repoURL: 'ssh://git@git.neozocloud.com:10022/tenants/hsp.git'
    path: argocd/prod/infrastructure/metrics-server
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metrics-server
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true

