# todo: clean up nonsense
qdrant:
  persistence:
    size: 20Gi
    storageClassName: gp3
  
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: qdrant.mllab.davidsfreun.de
        paths:
          - path: /
            pathType: Prefix
            servicePort: 6333
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"