apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: hsp
  sources:
    - repoURL: ssh://git@git.neozocloud.com:10022/tenants/hsp.git
      targetRevision: master
      ref: tenant_values

    - repoURL: ssh://git@git.neozocloud.com:10022/argocd/base.git
      targetRevision: HEAD
      ref: base_values

    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 5.45.1
      helm:
        valueFiles:
          - $base_values/argocd/values.yaml
          - $tenant_values/argocd/prod/infrastructure/argocd/values.yaml

    - repoURL: ssh://git@git.neozocloud.com:10022/tenants/hsp.git
      targetRevision: master
      path: argocd/prod/infrastructure/argocd/manifests/

    - repoURL: git@gitlab.crunchtime.net/devops/argocd.git
      targetRevision: main
      path: prod/argocd-manifests
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true