apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/saltandpurple/mllab_infrastructure"
    path: argocd/infrastructure/argocd
    targetRevision: MB/argocd
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true