apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: convex
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/saltandpurple/mllab_infrastructure"
      targetRevision: master
      ref: values
    - repoURL: "https://github.com/saltandpurple/helm-charts"
      path: convex
      targetRevision: master
      helm:
        valueFiles:
          - $values/convex/values.yaml
  destination:
    namespace: convex
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true