apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/saltandpurple/mllab_infrastructure"
    path: argocd/infrastructure/external-secrets
    targetRevision: master
  destination:
    namespace: external-secrets
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true