apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saltandpurple/mllab_infrastructure'
    path: argocd/infrastructure/ingress-nginx
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: ingress-nginx
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}