apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/saltandpurple/mllab_infrastructure"
    path: argocd/infrastructure/qdrant
    targetRevision: master
  destination:
    namespace: qdrant
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true