mlflow:
  postgresql:
    auth:
      existingSecret: "mlflow-postgresql"
  tracking:
    persistence:
      storageClass: gp3
    metrics:
      enabled: true
    ingress:
      enabled: true
    hostname: "mlflow.mllab.davidsfreun.de"
