mlflow:
  postgresql:
    auth:
      existingSecret: "mlflow-postgresql"
  tracking:
    auth:
      existingSecret: "mlflow-tracking"
    persistence:
      storageClass: gp3
    metrics:
      enabled: true
    service:
      type: "ClusterIP"
    ingress:
      enabled: true
      hostname: "mlflow.mllab.davidsfreun.de"
      ingressClassName: "nginx"
