apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: argocd-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /mllab/argocd/admin-pw
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-app
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "https://github.com/saltandpurple/mllab_infrastructure"
        project: default
        githubAppID: "{{ .githubAppId }}"
        githubAppInstallationID: "{{ .githubAppInstallationId }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: githubAppId
      remoteRef:
        key: /mllab/argocd/github-app-id
    - secretKey: githubAppInstallationId
      remoteRef:
        key: /mllab/argocd/github-app-installation-id
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: /mllab/argocd/github-app-private-key