apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chromadb-auth
  namespace: chromadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: chromadb-auth
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: /mllab/chromadb/token