apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: /mllab/example/api-key
  - secretKey: database-password
    remoteRef:
      key: /mllab/example/database-password
  - secretKey: config
    remoteRef:
      key: /mllab/example/config