apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-postgresql
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: mlflow-postgresql
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /mllab/mlflow/postgres-pw
  - secretKey: postgres-password
    remoteRef:
      key: /mllab/mlflow/postgres-pw
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-tracking
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: mlflow-tracking
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: /mllab/mlflow/admin-pw
    - secretKey: admin-user
      remoteRef:
        key: /mllab/mlflow/admin-user
    - secretKey: flask-server-secret-key
      remoteRef:
        key: /mllab/mlflow/flask-server-secret-key