apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-postgresql
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: mlflow-postgresql
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /mllab/mlflow/postgres-pw
  - secretKey: postgres-password
    remoteRef:
      key: /mllab/mlflow/postgres-pw