apiVersion: external-secrets.io/v1
metadata:
  name: aws-parameter-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      # The ESO controller uses the service account with IRSA annotations
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator