apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    external-secrets.io/disable-maintenance-checks: "true" # disable controller warning events for unmaintained stores
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      # The ESO controller uses the service account with IRSA annotations
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator