apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  annotations:
    external-secrets.io/disable-maintenance-checks: "true" # disable controller warning events for unmaintained stores
  name: aws-parameter-store
  namespace: external-secrets
spec:
  # todo: enable & test
#  conditions:
#    - namespaceSelector:
#        matchLabels:
#          kubernetes.io/metadata.name: mlflow
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets